server:
  port: 8081
app:
  security:
    trust-inbound-header: false
    public-routes:
      - /v1/auth/**
      - /webhook/**
      - /actuator/**
  ratelimit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 200

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              uri: ${MERCHANT_SERVICE_URI:lb://merchant-service}
              predicates:
                - Path=/v1/merchants/**, /v1/auth/**

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI:lb://payment-service}
              predicates:
                - Path=/v1/payments/**,/v1/orders/**
                
            - id: operations-service
              uri: ${OPERATIONS_SERVICE_URI:lb://operations-service}
              predicates:
                - Path=/webhook/**

            - id: vault-service
              uri: ${VAULT_SERVICE_URI:lb://vault-service}
              predicates: 
                - Path=/v1/vault/**
jwt:
  secret-key: sdfkjghdskljhbfvkeshfdnzkljgfdskujlzjfdslbkjfes

---

spring:
  config:
    activate:
      on-profile: k8s
jwt:
  secret-key: ${JWT_SECRET}

server.port: 8080
