spring:
  threads:
    virtual:
      enabled: true
  datasource:
    username: nithin
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: razorpay-clone-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.nithin.razorpay.*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}

feign:
  httpclient:
    hc5:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN
    zipkin2.reporter: DEBUG
    org.springframework.boot.zipkin: DEBUG
    io.micrometer.tracing: DEBUG




app:
  kafka:
    topics:
      payment: payment.events
      order: order.events
      refund: refund.events
      settlement: settlement.events
---

spring:
  config:
    activate:
      on-profile: k8s
  data:
    redis:
      host: redis.razorpay-core.svc.cluster.local
      port: 6379
  datasource:
    hikari:
      maximum-pool-size: 50
  kafka:
    bootstrap-servers: kafka.razorpay-core.svc.cluster.local:9092
  cloud:
    discovery:
      enabled: false
  task:
    scheduling:
      pool:
        size: 4

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

MERCHANT_SERVICE_URI: http://merchant-service
PAYMENT_SERVICE_URI: http://payment-service
VAULT_SERVICE_URI: http://vault-service
OPERATIONS_SERVICE_URI: http://operations-service
