server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/razorpay-merchant-db


jwt:
  secret-key: sdfkjghdskljhbfvkeshfdnzkljgfdskujlzjfdslbkjfes

webhook:
  secret-encryption-key: jEbSy97ac+f1IDJCbVEMOZ4CJ2VzScYQljWrkxwyVWs

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres.razorpay-core.svc.cluster.local:5432/razorpay-merchant-db
    username: merchant_user
    password: ${MERCHANT_DB_PASSSWORD}

  jwt:
    secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOL_SECRET_ENCRYPTION_KEY}
      
