server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-merchant-db


jwt:
  secret-key: sdfkjghdskljhbfvkeshfdnzkljgfdskujlzjfdslbkjfes

webhoook:
  secret-encryption-key: jEbSy97ac+f1IDJCbVEMOZ4CJ2VzScYQljWrkxwyVWs
