server:
  port: 9030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/razorpay-operations-db

app:
  webhook:
    delivery:
      redis-key: "webhook-retry"
      poll-batch-size: 100
