server:
  port: 9040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/razorpay-vault-db

vault:
  master-key: NqcfbJG1zkOfBsNF/wPmlLA7aaOvh9RCHTYYgY/9A2Q=

resilience4j:
  thread-pool-bulkhead:
    instances:
      vault-card-processor:
        core-thread-pool-size: 5
        max-thread-pool-size: 10
        queue-capacity: 20
